const LOCAL_INVOICE_NUMBER = 'invoice_number';
const LOCAL_SUBTOTAL = 'subtotal';
const LOCAL_DISCOUNT_PERCENT = 'discount_percent';
const LOCAL_TOTAL = 'total';
const LOCAL_IBAN_NUMBER = 'IBAN_number';
const LOCAL_ITEMS_TABLE = 'itemsTable';
const LOCAL_ITEM_QTY = 'itemQty';
const LOCAL_ITEM_COST = 'itemCost';
const LOCAL_ITEM_TOTAL = 'itemCost';
const LOCAL_ITEM_TITLE = 'item_title';
const LOCAL_ITEM_DESCRIPTION = 'item_description';

export { LOCAL_INVOICE_NUMBER, LOCAL_SUBTOTAL, LOCAL_DISCOUNT_PERCENT, LOCAL_TOTAL, LOCAL_IBAN_NUMBER, LOCAL_ITEMS_TABLE, LOCAL_ITEM_QTY, LOCAL_ITEM_COST, LOCAL_ITEM_TOTAL, LOCAL_ITEM_TITLE, LOCAL_ITEM_DESCRIPTION };
